-- Authoritative record-model migration for the pi861 memory store.
-- Apply with a MIGRATION role (schema owner), not the model-facing runtime role.
-- Additive over memory-v1.sql: existing tables keep their identities; bodies are
-- converted in place by the migration tool (src/live/memory-migration.ts), which
-- also records this version in the pi861_schema_migrations ledger.
BEGIN;

-- Migration ledger: one row per applied version. The migration tool verifies the
-- file digest before skipping an applied version; a changed digest is an error.
CREATE TABLE IF NOT EXISTS pi861_schema_migrations (
  version text PRIMARY KEY,
  name text NOT NULL,
  digest text NOT NULL,
  applied_at timestamptz NOT NULL DEFAULT clock_timestamp()
);

-- Receipt hashes from explicitly imported legacy stores remain replayable.
CREATE TABLE IF NOT EXISTS pi861_memory_legacy_receipts (
  tenant_id text NOT NULL, principal_id text NOT NULL, request_id text NOT NULL,
  scope_key text NOT NULL, intent_hash text NOT NULL,
  PRIMARY KEY (tenant_id, principal_id, request_id)
);
CREATE TABLE IF NOT EXISTS pi861_memory_imports (
  source_id text PRIMARY KEY, digest text NOT NULL,
  imported_at timestamptz NOT NULL DEFAULT clock_timestamp()
);

-- Derived summaries bound to the source revision that produced them.
CREATE TABLE IF NOT EXISTS pi861_memory_projections (
  tenant_id text NOT NULL,
  scope_key text NOT NULL,
  memory_id text NOT NULL,
  source_revision bigint NOT NULL CHECK (source_revision > 0),
  abstract text NOT NULL,
  overview text NOT NULL,
  facts jsonb NOT NULL,
  model_id text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY (tenant_id, scope_key, memory_id)
);

-- Durable extraction jobs: state machine queued/running/done/obsolete/failed with
-- lease tokens, bounded failures, backoff scheduling and a manual requeue path.
CREATE TABLE IF NOT EXISTS pi861_memory_jobs (
  tenant_id text NOT NULL,
  job_id text NOT NULL,
  scope_key text NOT NULL,
  memory_id text NOT NULL,
  source_revision bigint NOT NULL CHECK (source_revision > 0),
  state text NOT NULL DEFAULT 'queued' CHECK (state IN ('queued','running','done','obsolete','failed')),
  attempts int NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  failures int NOT NULL DEFAULT 0 CHECK (failures >= 0),
  failure_class text CHECK (failure_class IN ('transient','permanent','invalid_output')),
  next_attempt_at timestamptz,
  lease_token text,
  lease_expires_at timestamptz,
  max_attempts int NOT NULL DEFAULT 3 CHECK (max_attempts >= 1),
  requeues int NOT NULL DEFAULT 0 CHECK (requeues >= 0),
  last_error text,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  finished_at timestamptz,
  PRIMARY KEY (tenant_id, job_id)
);
CREATE INDEX IF NOT EXISTS pi861_memory_jobs_claim
  ON pi861_memory_jobs (tenant_id, created_at, job_id) WHERE state IN ('queued','running');

-- Monotonic change feed and transactional outbox in one table: appended in the
-- same transaction as the state change, sequence drives incremental cursors, the
-- state machine drives at-least-once consumers (index rebuild, cache invalidation).
-- Supersedes pi861_memory_outbox as the consumer feed; the v1 table is retained
-- unchanged for compatibility and is converted by the migration tool.
CREATE TABLE IF NOT EXISTS pi861_memory_events (
  tenant_id text NOT NULL,
  sequence bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scope_key text NOT NULL,
  memory_id text NOT NULL,
  revision bigint NOT NULL CHECK (revision > 0),
  action text NOT NULL CHECK (action IN ('put','withdraw','projection')),
  event_digest text NOT NULL,
  state text NOT NULL DEFAULT 'pending' CHECK (state IN ('pending','dispatched','failed')),
  attempts int NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  next_attempt_at timestamptz,
  last_error text,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  UNIQUE (tenant_id, event_digest)
);
CREATE INDEX IF NOT EXISTS pi861_memory_events_feed
  ON pi861_memory_events (tenant_id, sequence, scope_key);

-- Scope dimension and purpose index on the authoritative items table. Purpose
-- tolerates pre-migration bodies that still use the kernel "kind" key.
ALTER TABLE pi861_memory_items ADD COLUMN IF NOT EXISTS scope_kind text
  GENERATED ALWAYS AS (split_part(scope_key, ':', 1)) STORED;
ALTER TABLE pi861_memory_items ADD COLUMN IF NOT EXISTS purpose text
  GENERATED ALWAYS AS (coalesce(body->>'purpose', body->>'kind')) STORED;
CREATE INDEX IF NOT EXISTS pi861_memory_items_purpose
  ON pi861_memory_items (tenant_id, scope_key, purpose, memory_id);
-- Canonical C1 scope shape, enforced for new writes; NOT VALID so pre-migration
-- rows do not block the ALTER - the migration tool reports them as conflicts.
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'pi861_scope_canonical' AND conrelid = 'pi861_memory_items'::regclass) THEN
    ALTER TABLE pi861_memory_items ADD CONSTRAINT pi861_scope_canonical
      CHECK (scope_key ~ '^(user|project|group|agent|task|shared):[a-z0-9][a-z0-9._/-]{0,200}$') NOT VALID;
  END IF;
END $$;

-- Row level security for the new tables, mirroring the v1 boundary: read through
-- the session read scopes, write only through the write scopes.
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['pi861_memory_projections', 'pi861_memory_jobs', 'pi861_memory_events'] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = current_schema() AND tablename = t AND policyname = 'pi861_scope') THEN
      EXECUTE format(
        'CREATE POLICY pi861_scope ON %I USING
         (tenant_id = current_setting(''pi861.tenant_id'', true)
          AND scope_key IN (SELECT jsonb_array_elements_text(coalesce(nullif(current_setting(''pi861.read_scopes'', true), ''''), ''[]'')::jsonb)))
         WITH CHECK
         (tenant_id = current_setting(''pi861.tenant_id'', true)
          AND scope_key IN (SELECT jsonb_array_elements_text(coalesce(nullif(current_setting(''pi861.write_scopes'', true), ''''), ''[]'')::jsonb)))', t);
    END IF;
  END LOOP;
END $$;

ALTER TABLE pi861_memory_legacy_receipts ENABLE ROW LEVEL SECURITY;
ALTER TABLE pi861_memory_legacy_receipts FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS pi861_legacy_receipt_owner ON pi861_memory_legacy_receipts;
CREATE POLICY pi861_legacy_receipt_owner ON pi861_memory_legacy_receipts FOR SELECT USING (
  tenant_id=current_setting('pi861.tenant_id',true) AND principal_id=current_setting('pi861.principal_id',true)
  AND scope_key IN (SELECT jsonb_array_elements_text(coalesce(nullif(current_setting('pi861.read_scopes',true),''),'[]')::jsonb))
);
-- A read grant must never authorize DELETE. Split policies: USING on mutation
-- paths checks write scopes as well as WITH CHECK. Apply to v1 and v3 tables.
DO $$ DECLARE t text; BEGIN
  FOREACH t IN ARRAY ARRAY['pi861_memory_items','pi861_memory_versions','pi861_memory_tombstones','pi861_memory_outbox','pi861_memory_projections','pi861_memory_jobs','pi861_memory_events'] LOOP
    EXECUTE format('DROP POLICY IF EXISTS pi861_scope ON %I',t);
    EXECUTE format('DROP POLICY IF EXISTS pi861_read ON %I',t);
    EXECUTE format('DROP POLICY IF EXISTS pi861_write ON %I',t);
    EXECUTE format('CREATE POLICY pi861_read ON %I FOR SELECT USING (tenant_id=current_setting(''pi861.tenant_id'',true) AND scope_key IN (SELECT jsonb_array_elements_text(coalesce(nullif(current_setting(''pi861.read_scopes'',true),''''),''[]'')::jsonb)))',t);
    EXECUTE format('CREATE POLICY pi861_write ON %I FOR ALL USING (tenant_id=current_setting(''pi861.tenant_id'',true) AND scope_key IN (SELECT jsonb_array_elements_text(coalesce(nullif(current_setting(''pi861.write_scopes'',true),''''),''[]'')::jsonb))) WITH CHECK (tenant_id=current_setting(''pi861.tenant_id'',true) AND scope_key IN (SELECT jsonb_array_elements_text(coalesce(nullif(current_setting(''pi861.write_scopes'',true),''''),''[]'')::jsonb)))',t);
  END LOOP;
END $$;

COMMIT;
-- Provision SELECT/INSERT/UPDATE on runtime tables, DELETE on projections/jobs
-- only, and USAGE/SELECT on the events identity sequence. Ledger, import metadata
-- and legacy receipt markers are migration-owned; runtime needs SELECT only.
